AWSTemplateFormatVersion: 2010-09-09
Description: Create ec2 

Parameters:
  itype:
    Description: the size of instance
    Type: String
    Default: t2.micro

  keyname:
    Description: name of your key
    Type: String
    Default: your-key-name

  ec2name:
    Description: name of your instance
    Type: String
    Default: your-instance-name

Resources:
  Myec2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref itype
      KeyName: !Ref keyname
      AvailabilityZone: us-east-1a
      ImageId: ami-0e449927258d45bc4

      Tags:
        - Key: Name
          Value: !Ref ec2name
  