AWSTemplateFormatVersion: 2010-09-09
Description: hw assignment.Create users, group, and assign permissions with CloudFormation

Resources:
  jakeusr:
    Type: AWS::IAM::User
    Properties:
      UserName: jake

  paulusr:
    Type: AWS::IAM::User
    Properties: 
      Username: paul

  cfngroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: cfngroup
      ManagedPolicyArns:  
       - arn:aws:iam::aws:policy/AmazonEC2FullAccess
       - arn:aws:iam::aws:policy/IAMFullAccess

    Type: AWS::IAM::UserToGroupAddition
    Properties:
     GroupName: !Ref cfngroup
     Users:
        - !Ref paulusr
        - !Ref jakeusr