AWSTemplateFormatVersion: 2010-09-09
Description: hw assignment. create ec2 t2.micro

Resources:
  ec2instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: VM1
      AvailabilityZone: us-east-1a
      ImageId: ami-0e449927258d45bc4 
      Tags: 
        - Key: Name
        - Value: CFN-EC2
